# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZTO-5yx8KDoWjpIkWVTxSYJtDNDd3lP
"""


"Name = Mo"

"Country = USA"

'Age = 25'

"hourly_wage = 40"

"satisfied = true"

"daily wage = 'hourly_wage'*8"

a = [1,100,1000,10000,100000]
len(a)

for i in range(10):
  print(i)

tu = (1,3)

tu

print(f'Hello')

